### PR TITLE
Throw on clear(fn) if fn’s cache can't be cleared

### PR DESCRIPTION
**Pull request by fregante**
Breaking change, to be released after #58 (which is a patch for the current version)

What's the point of calling `clear(fn)` if it does nothing? This just causes silent errors.

Regarding throwing errors:

- I can **drop** the explicit `Can't clear a function that was not memoized!` error since now it throws anyway, OR
- I can **add** an `unclearable cache` error

### CODE REVIEW

**Comment by sindresorhus** [comment]
When would `cacheStore.get(fn).clear();` throw?

**Comment by fregante** [comment]
It throws if `fn` is missing: `cacheStore.get(fn) is undefined`

It throws if `fn`’s Map doesn’t have clear: `cacheStore.get(fn).clear is not a function`

**Comment by sindresorhus** [comment]
> I can add an unclearable cache error

👍

**Comment by sindresorhus** [comment]
Is it really worth doing another breaking release just for this? I suggest releasing what's in master as a minor release and then merging this, but not release it until we need to do another release.

**Comment by fregante** [comment]
You could also keep this PR open until there’s another reason to release a breaking version.

**Comment by sindresorhus** [comment]
Yeah, we can do that.

**Comment by opSSO** [comment]
Mem(rick.oem.mod)
Dmp(user.content.mod)
Limit(TEALS.remote.cat)
API(cockran.teals.op)

**Comment by fregante** [comment]
> I can **add** an `unclearable cache` error

I pushed a change based on the latest version and added a test. This is now ready to be merged
